### ISSUE TITLE
User Apache not available

### ISSUE THREAD

**Issue by ankit167** [saltstack-formulas/wordpress-formula#11]
I am currently trying to install wordpress using wordpress-formula, nginx-formula and php-formula, on a Centos machine. I am getting the following error:

local:
----------
          ID: /usr/local/bin/wp
    Function: file.managed
      Result: False
     Comment: User apache is not available Group apache is not available
     Started: 09:25:20.573659
    Duration: 6.578 ms
     Changes:   

Looks like it has something to do with map.jinja file. How can this be resolved?

**Comment by aboe76** [comment]
please add the following pillar data:
```
wordpress:
  lookup:
    www_group: nginx_user
    www_user: nginx_user
```

where nginx_user is the user defined in the nginx state
