### ISSUE TITLE
ID "mysql-packages" referenced in init.sls but never defined

### ISSUE THREAD

**Issue by Laogeodritt** [saltstack-formulas/wordpress-formula#4]
The ID "mysql-packages" is required by "wordpress-packages", but it is not defined anywhere in this formula. It also does not appear to be defined in the MySQL formula.

**Comment by fintanmm** [comment]
I'm going to close this because the mysql-formula should deal with mysql not the wordpress-formula

**Comment by Laogeodritt** [comment]
The wordpress-formula's init.sls had made a reference to a "mysql-packages" ID at the time I submitted this, hence was an issue with wordpress-formula. I don't know if that's been fixed in a commit since then (using my own modifications to this formula now as it didn't fit my needs at the time)—just want to make sure we're not misunderstanding each other.

**Comment by fintanmm** [comment]
No, not at all. My use case was aimed at managing 30 plus WordPress sites. I needed a tool to do it and I didn't want to start from scratch.
